steps:
- name: 'mcr.microsoft.com/dotnet/sdk:7.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    dotnet publish -c Release -o ./publish

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'app'
  - 'deploy'
  - './publish/app.yaml'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  
timeout: "1200s"
